### ISSUE TITLE
'ascii' codec can't encode character u'\xfc'

### ISSUE THREAD

**Issue by bauigel** [Bytespeicher/ics2mailinglist#1]
If i try to fetch the bytespeicher-ics and send it through gmail-smpt, i get an encode-error while sending...

> UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 512: ordinal not in range(128)

**Comment by suicider** [comment]
I can confirm this issue. It's probably the "é" from Repaircafé and every other unicode character where the encoding fails.

**Comment by bauigel** [comment]
Hope i found a soulution. We have to encode content from ics bevor generating content.

```
Line 46: mail += 'Betreff:      ' + ev.get('summary').encode('utf-8') + "\n"
Line 51: mail += "\n".join(wrap(ev.get('description').encode('utf-8'), 65, subsequent_indent=(' ' * 14)))
```

**Comment by suicider** [comment]
Unfortunately not. I had the same idea but it's still wrong:
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 24: ordinal not in range(128)

I'll work on that and provide a fix as soon as possible.

**Comment by suicider** [comment]
Well, your proposal was right, my mistake.
