### ISSUE TITLE
SMTP Server SSL or no SSL

### ISSUE THREAD

**Issue by dslater82** [Bytespeicher/ics2mailinglist#7]
Config option to set SSL or no SSL for sending email.

I cneeded to change 
server = smtplib.SMTP_SSL(host=smtp_server) 
to
server = smtplib.SMTP(host=smtp_server)

to get it to work.

**Comment by izzy** [comment]
Could you write something that would make this configurable through a boolean variable(defaulting to `True` to be consistent) in config.py and pull request it?
